spring:
  application.name: splearn
  datasource:
    url: jdbc:mysql://localhost:3306/z_example_splearn
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
  docker:
    compose:
      lifecycle-management: start_only